/**
 * Local Legend blend chrome for each client package skin.
 * Charcoal, white, teal, slate. Gold colors are only applied to skins
 * whose shared tier is "top" (see packageSkins.ts).
 */

import type { ListingCardLook } from "@shared/listingCard";

export interface SkinTheme {
  radiusClass: string;
  background: string;
  border: string;
  shadow: string;
  heroClass: string;
  fade: string;
  badgeClass: string;
  panelClass: string;
  titleClass: string;
  accentClass: string;
  featuresClass: string;
  streetClass: string;
  cityClass: string;
  amenityClass: string;
  chipClass: string;
  chipGoldClass: string;
  chipTealClass: string;
  priceClass: string;
  shootClass: string;
  photoClass: string;
  placeholderClass: string;
}

const CHIP = "border";
const GOLD_CHIP = `${CHIP} border-[rgba(201,162,39,0.5)] text-[#e8d5a3] bg-[rgba(201,162,39,0.08)]`;
const TEAL_CHIP = `${CHIP} border-[rgba(94,234,212,0.4)] text-[#5eead4] bg-[rgba(13,148,136,0.12)]`;
const TEAL_SOFT_CHIP = `${CHIP} border-[#0d9488] text-[#0f766e] bg-[#f0fdfa]`;

const lightStreet = "text-[14px] font-bold tracking-[-0.01em] leading-tight text-[#0F172A]";
const lightCity = "mt-0.5 text-[12px] font-medium text-[#64748b]";
const darkStreet = "text-[14px] font-bold tracking-[-0.01em] leading-tight text-white";
const darkCity = "mt-0.5 text-[12px] font-medium text-[#5eead4]";

function theme(partial: SkinTheme): SkinTheme {
  return partial;
}

export const SKIN_THEMES: Record<ListingCardLook, SkinTheme> = {
  apprenticeship: theme({
    radiusClass: "rounded-[10px]",
    background: "#f1f5f9",
    border: "1px solid #cbd5e1",
    shadow: "none",
    heroClass: "h-[200px]",
    fade: "linear-gradient(180deg, transparent, #f1f5f9)",
    badgeClass: "bg-[rgba(15,23,42,0.45)] font-semibold tracking-[0.1em] text-[#e2e8f0]",
    panelClass: "bg-[#f1f5f9] text-[#64748b]",
    titleClass: "text-[16px] font-semibold tracking-[0.04em] text-[#64748b]",
    accentClass: "text-[#64748b]",
    featuresClass: "font-normal text-[#94a3b8]",
    streetClass: "text-[13px] font-semibold leading-tight text-[#64748b]",
    cityClass: "mt-0.5 text-[12px] font-medium text-[#94a3b8]",
    amenityClass: "text-[#64748b]",
    chipClass: `${CHIP} border-[#cbd5e1] text-[#64748b] bg-[#f8fafc]`,
    chipGoldClass: GOLD_CHIP,
    chipTealClass: TEAL_CHIP,
    priceClass: "text-[18px] font-bold text-[#64748b]",
    shootClass: "text-[10px] font-medium text-[#94a3b8]",
    photoClass: "grayscale contrast-90 brightness-105",
    placeholderClass: "bg-gradient-to-b from-slate-400 to-slate-600",
  }),
  "just-photos": theme({
    radiusClass: "rounded-[18px]",
    background: "#ffffff",
    border: "1px solid #94a3b8",
    shadow: "none",
    heroClass: "h-[210px]",
    fade: "linear-gradient(180deg, transparent, #ffffff)",
    badgeClass: "bg-[rgba(15,23,42,0.55)] font-extrabold tracking-[0.18em] text-white",
    panelClass: "bg-white text-[#0F172A]",
    titleClass: "text-[18px] font-bold text-[#0F172A]",
    accentClass: "text-[#0F172A]",
    featuresClass: "font-medium text-[#64748b]",
    streetClass: lightStreet,
    cityClass: lightCity,
    amenityClass: "text-[#1e293b]",
    chipClass: `${CHIP} border-[#94a3b8] text-[#0F172A] bg-transparent`,
    chipGoldClass: GOLD_CHIP,
    chipTealClass: TEAL_CHIP,
    priceClass: "text-[18px] font-extrabold text-[#0F172A]",
    shootClass: "text-[10px] font-bold text-[#0F172A]",
    photoClass: "[filter:saturate(0.75)_contrast(0.95)]",
    placeholderClass: "bg-gradient-to-b from-slate-300 to-slate-500",
  }),
  essentials: theme({
    radiusClass: "rounded-[18px]",
    background: "#ffffff",
    border: "2px solid #0F172A",
    shadow: "0 10px 24px rgba(15,23,42,0.12)",
    heroClass: "h-[210px]",
    fade: "linear-gradient(180deg, transparent, #ffffff)",
    badgeClass: "bg-[#0F172A] font-extrabold tracking-[0.18em] text-white",
    panelClass: "bg-white text-[#0F172A]",
    titleClass: "text-[20px] font-extrabold text-[#0F172A]",
    accentClass: "text-[#0F172A]",
    featuresClass: "font-medium text-[#334155]",
    streetClass: lightStreet,
    cityClass: lightCity,
    amenityClass: "text-[#1e293b]",
    chipClass: `${CHIP} border-[#0F172A] text-[#0F172A] bg-transparent`,
    chipGoldClass: GOLD_CHIP,
    chipTealClass: TEAL_CHIP,
    priceClass: "text-[22px] font-extrabold text-[#0F172A]",
    shootClass: "text-[10px] font-bold text-[#0F172A]",
    photoClass: "",
    placeholderClass: "bg-gradient-to-b from-sky-400 to-slate-200",
  }),
  showcase: theme({
    radiusClass: "rounded-[18px]",
    background: "#ffffff",
    border: "2px solid #0d9488",
    shadow: "0 14px 30px rgba(13,148,136,0.18)",
    heroClass: "h-[210px]",
    fade: "linear-gradient(180deg, transparent, #ffffff)",
    badgeClass: "bg-[#0d9488] font-extrabold tracking-[0.18em] text-white",
    panelClass: "bg-white text-[#0F172A]",
    titleClass: "text-[22px] font-extrabold text-[#0f766e]",
    accentClass: "text-[#0f766e]",
    featuresClass: "font-medium text-[#334155]",
    streetClass: lightStreet,
    cityClass: lightCity,
    amenityClass: "text-[#1e293b]",
    chipClass: TEAL_SOFT_CHIP,
    chipGoldClass: GOLD_CHIP,
    chipTealClass: TEAL_SOFT_CHIP,
    priceClass: "text-[22px] font-extrabold text-[#0f766e]",
    shootClass: "text-[10px] font-bold text-[#0F172A]",
    photoClass: "",
    placeholderClass: "bg-gradient-to-b from-cyan-700 via-sky-200 to-teal-800",
  }),
  legacy: theme({
    radiusClass: "rounded-[18px]",
    background: "#0F172A",
    border: "1px solid rgba(201,162,39,0.45)",
    shadow: "0 18px 40px rgba(15,23,42,0.45), 0 0 0 1px rgba(13,148,136,0.35)",
    heroClass: "h-[210px]",
    fade: "linear-gradient(180deg, transparent, #0F172A)",
    badgeClass: "border border-[rgba(201,162,39,0.55)] bg-[rgba(15,23,42,0.65)] font-extrabold tracking-[0.18em] text-[#e8d5a3]",
    panelClass: "bg-[#0F172A] text-white",
    titleClass: "text-[22px] font-extrabold text-white",
    accentClass: "text-[#e8d5a3]",
    featuresClass: "font-medium text-[#94a3b8]",
    streetClass: darkStreet,
    cityClass: darkCity,
    amenityClass: "text-white",
    chipClass: GOLD_CHIP,
    chipGoldClass: GOLD_CHIP,
    chipTealClass: TEAL_CHIP,
    priceClass: "text-[22px] font-extrabold text-[#e8d5a3]",
    shootClass: "text-[10px] font-bold text-white",
    photoClass: "",
    placeholderClass: "bg-gradient-to-b from-orange-900 via-slate-800 to-slate-950",
  }),
  "market-leader": theme({
    radiusClass: "rounded-[18px]",
    background: "#020617",
    border: "1px solid rgba(13,148,136,0.55)",
    shadow: "0 22px 48px rgba(13,148,136,0.3), 0 0 0 1px rgba(201,162,39,0.35)",
    heroClass: "h-[210px]",
    fade: "linear-gradient(180deg, transparent, #020617)",
    badgeClass: "border border-[rgba(201,162,39,0.4)] bg-gradient-to-r from-[#0f766e] to-[#1e293b] font-extrabold tracking-[0.18em] text-[#e8d5a3]",
    panelClass: "bg-[#020617] text-white",
    titleClass: "text-[20px] font-extrabold text-white",
    accentClass: "text-[#5eead4]",
    featuresClass: "font-medium text-[#94a3b8]",
    streetClass: darkStreet,
    cityClass: darkCity,
    amenityClass: "text-white",
    chipClass: TEAL_CHIP,
    chipGoldClass: `${CHIP} border-[rgba(201,162,39,0.55)] text-[#e8d5a3] bg-[rgba(201,162,39,0.1)]`,
    chipTealClass: TEAL_CHIP,
    priceClass: "text-[22px] font-extrabold text-[#e8d5a3]",
    shootClass: "text-[10px] font-bold text-white",
    photoClass: "",
    placeholderClass: "bg-gradient-to-b from-slate-900 via-teal-950 to-black",
  }),
  refresh: theme({
    radiusClass: "rounded-[18px]",
    background: "#ffffff",
    border: "1px solid #cbd5e1",
    shadow: "0 6px 16px rgba(15,23,42,0.08)",
    heroClass: "h-[210px]",
    fade: "linear-gradient(180deg, transparent, #ffffff)",
    badgeClass: "bg-[#0d9488] font-extrabold tracking-[0.18em] text-white",
    panelClass: "bg-white text-[#0F172A]",
    titleClass: "text-[20px] font-extrabold text-[#0F172A]",
    accentClass: "text-[#0F172A]",
    featuresClass: "font-medium text-[#64748b]",
    streetClass: lightStreet,
    cityClass: lightCity,
    amenityClass: "text-[#334155]",
    chipClass: `${CHIP} border-[#cbd5e1] text-[#334155] bg-[#f8fafc]`,
    chipGoldClass: GOLD_CHIP,
    chipTealClass: TEAL_CHIP,
    priceClass: "text-[22px] font-extrabold text-[#0F172A]",
    shootClass: "text-[10px] font-bold text-[#64748b]",
    photoClass: "",
    placeholderClass: "bg-gradient-to-b from-slate-400 to-slate-600",
  }),
  "content-partner": theme({
    radiusClass: "rounded-[18px]",
    background: "#1e293b",
    border: "1px solid rgba(13,148,136,0.45)",
    shadow: "0 14px 32px rgba(13,148,136,0.22)",
    heroClass: "h-[210px]",
    fade: "linear-gradient(180deg, transparent, #1e293b)",
    badgeClass: "bg-[#0d9488] font-extrabold tracking-[0.18em] text-white",
    panelClass: "bg-[#1e293b] text-white",
    titleClass: "text-[22px] font-extrabold text-white",
    accentClass: "text-white",
    featuresClass: "font-medium text-[#94a3b8]",
    streetClass: darkStreet,
    cityClass: "mt-0.5 text-[12px] font-medium text-[#94a3b8]",
    amenityClass: "text-white",
    chipClass: TEAL_CHIP,
    chipGoldClass: GOLD_CHIP,
    chipTealClass: TEAL_CHIP,
    priceClass: "text-[22px] font-extrabold text-[#5eead4]",
    shootClass: "text-[10px] font-bold text-[#94a3b8]",
    photoClass: "",
    placeholderClass: "bg-gradient-to-b from-slate-600 to-slate-900",
  }),
  "local-legend": theme({
    radiusClass: "rounded-[18px]",
    background: "#0F172A",
    border: "1px solid rgba(201,162,39,0.4)",
    shadow: "0 20px 44px rgba(15,23,42,0.5), 0 0 0 1px rgba(13,148,136,0.25)",
    heroClass: "h-[210px]",
    fade: "linear-gradient(180deg, transparent, #0F172A)",
    badgeClass: "border border-[rgba(201,162,39,0.55)] bg-[rgba(15,23,42,0.7)] font-extrabold tracking-[0.18em] text-[#e8d5a3]",
    panelClass: "bg-[#0F172A] text-white",
    titleClass: "text-[24px] font-extrabold text-white",
    accentClass: "text-[#e8d5a3]",
    featuresClass: "font-medium text-[#94a3b8]",
    streetClass: darkStreet,
    cityClass: darkCity,
    amenityClass: "text-white",
    chipClass: GOLD_CHIP,
    chipGoldClass: GOLD_CHIP,
    chipTealClass: TEAL_CHIP,
    priceClass: "text-[22px] font-extrabold text-[#e8d5a3]",
    shootClass: "text-[10px] font-bold text-[#94a3b8]",
    photoClass: "",
    placeholderClass: "bg-gradient-to-br from-orange-600 to-slate-950",
  }),
  baseline: theme({
    radiusClass: "rounded-[18px]",
    background: "#ffffff",
    border: "1px solid #cbd5e1",
    shadow: "none",
    heroClass: "h-[210px]",
    fade: "linear-gradient(180deg, transparent, #ffffff)",
    badgeClass: "bg-[#e2e8f0] font-extrabold tracking-[0.18em] text-[#334155]",
    panelClass: "bg-white text-[#0F172A]",
    titleClass: "text-[18px] font-bold text-[#0F172A]",
    accentClass: "text-[#0F172A]",
    featuresClass: "font-medium text-[#64748b]",
    streetClass: lightStreet,
    cityClass: lightCity,
    amenityClass: "text-[#334155]",
    chipClass: `${CHIP} border-[#cbd5e1] text-[#64748b] bg-[#f8fafc]`,
    chipGoldClass: GOLD_CHIP,
    chipTealClass: TEAL_CHIP,
    priceClass: "text-[20px] font-extrabold text-[#0F172A]",
    shootClass: "text-[10px] font-bold text-[#64748b]",
    photoClass: "",
    placeholderClass: "bg-gradient-to-b from-amber-100 to-slate-300",
  }),
  "growth-engine": theme({
    radiusClass: "rounded-[18px]",
    background: "#ffffff",
    border: "2px solid #0d9488",
    shadow: "0 10px 24px rgba(13,148,136,0.16)",
    heroClass: "h-[210px]",
    fade: "linear-gradient(180deg, transparent, #ffffff)",
    badgeClass: "bg-[#0d9488] font-extrabold tracking-[0.18em] text-white",
    panelClass: "bg-white text-[#0F172A]",
    titleClass: "text-[22px] font-extrabold text-[#0f766e]",
    accentClass: "text-[#0f766e]",
    featuresClass: "font-medium text-[#334155]",
    streetClass: lightStreet,
    cityClass: lightCity,
    amenityClass: "text-[#1e293b]",
    chipClass: TEAL_SOFT_CHIP,
    chipGoldClass: GOLD_CHIP,
    chipTealClass: TEAL_SOFT_CHIP,
    priceClass: "text-[22px] font-extrabold text-[#0f766e]",
    shootClass: "text-[10px] font-bold text-[#334155]",
    photoClass: "",
    placeholderClass: "bg-gradient-to-b from-slate-800 to-slate-950",
  }),
  "professional-suite": theme({
    radiusClass: "rounded-[18px]",
    background: "#1e293b",
    border: "1px solid #475569",
    shadow: "0 12px 28px rgba(15,23,42,0.28)",
    heroClass: "h-[210px]",
    fade: "linear-gradient(180deg, transparent, #1e293b)",
    badgeClass: "bg-white font-extrabold tracking-[0.18em] text-[#0F172A]",
    panelClass: "bg-[#1e293b] text-white",
    titleClass: "text-[22px] font-extrabold text-white",
    accentClass: "text-white",
    featuresClass: "font-medium text-[#94a3b8]",
    streetClass: darkStreet,
    cityClass: "mt-0.5 text-[12px] font-medium text-[#94a3b8]",
    amenityClass: "text-white",
    chipClass: `${CHIP} border-[#64748b] text-[#e2e8f0] bg-[rgba(255,255,255,0.06)]`,
    chipGoldClass: GOLD_CHIP,
    chipTealClass: TEAL_CHIP,
    priceClass: "text-[22px] font-extrabold text-white",
    shootClass: "text-[10px] font-bold text-[#94a3b8]",
    photoClass: "",
    placeholderClass: "bg-gradient-to-b from-slate-600 to-slate-900",
  }),
  "signature-tier": theme({
    radiusClass: "rounded-[18px]",
    background: "#042f2e",
    border: "1px solid rgba(13,148,136,0.5)",
    shadow: "0 16px 36px rgba(13,148,136,0.28)",
    heroClass: "h-[210px]",
    fade: "linear-gradient(180deg, transparent, #042f2e)",
    badgeClass: "border border-[rgba(94,234,212,0.45)] bg-[rgba(13,148,136,0.25)] font-extrabold tracking-[0.18em] text-[#5eead4]",
    panelClass: "bg-[#042f2e] text-white",
    titleClass: "text-[22px] font-extrabold text-white",
    accentClass: "text-white",
    featuresClass: "font-medium text-[#99f6e4]/85",
    streetClass: darkStreet,
    cityClass: darkCity,
    amenityClass: "text-white",
    chipClass: `${CHIP} border-[rgba(94,234,212,0.4)] text-[#5eead4] bg-[rgba(13,148,136,0.15)]`,
    chipGoldClass: GOLD_CHIP,
    chipTealClass: TEAL_CHIP,
    priceClass: "text-[22px] font-extrabold text-[#5eead4]",
    shootClass: "text-[10px] font-bold text-[#5eead4]",
    photoClass: "",
    placeholderClass: "bg-gradient-to-b from-teal-900 to-[#042f2e]",
  }),
  "iconic-partnership": theme({
    radiusClass: "rounded-[18px]",
    background: "#0F172A",
    border: "1px solid rgba(201,162,39,0.5)",
    shadow: "0 22px 48px rgba(15,23,42,0.5), 0 0 0 1px rgba(13,148,136,0.3)",
    heroClass: "h-[210px]",
    fade: "linear-gradient(180deg, transparent, #0F172A)",
    badgeClass: "border border-[rgba(201,162,39,0.55)] bg-[rgba(15,23,42,0.75)] font-extrabold tracking-[0.18em] text-[#e8d5a3]",
    panelClass: "bg-[#0F172A] text-white",
    titleClass: "text-[20px] font-extrabold text-white",
    accentClass: "text-[#e8d5a3]",
    featuresClass: "font-medium text-[#94a3b8]",
    streetClass: darkStreet,
    cityClass: darkCity,
    amenityClass: "text-white",
    chipClass: GOLD_CHIP,
    chipGoldClass: GOLD_CHIP,
    chipTealClass: TEAL_CHIP,
    priceClass: "text-[22px] font-extrabold text-[#e8d5a3]",
    shootClass: "text-[10px] font-bold text-[#94a3b8]",
    photoClass: "",
    placeholderClass: "bg-gradient-to-b from-amber-900 to-slate-950",
  }),
  "connected-core": theme({
    radiusClass: "rounded-[18px]",
    background: "#ffffff",
    border: "2px solid #334155",
    shadow: "0 10px 24px rgba(15,23,42,0.12)",
    heroClass: "h-[210px]",
    fade: "linear-gradient(180deg, transparent, #ffffff)",
    badgeClass: "bg-[#334155] font-extrabold tracking-[0.18em] text-white",
    panelClass: "bg-white text-[#0F172A]",
    titleClass: "text-[22px] font-extrabold text-[#0F172A]",
    accentClass: "text-[#0F172A]",
    featuresClass: "font-medium text-[#334155]",
    streetClass: lightStreet,
    cityClass: lightCity,
    amenityClass: "text-[#1e293b]",
    chipClass: `${CHIP} border-[#334155] text-[#0F172A] bg-[#f8fafc]`,
    chipGoldClass: GOLD_CHIP,
    chipTealClass: TEAL_CHIP,
    priceClass: "text-[22px] font-extrabold text-[#0F172A]",
    shootClass: "text-[10px] font-bold text-[#0F172A]",
    photoClass: "",
    placeholderClass: "bg-gradient-to-b from-slate-400 to-slate-700",
  }),
  "authority-stack": theme({
    radiusClass: "rounded-[18px]",
    background: "#020617",
    border: "1px solid rgba(201,162,39,0.45)",
    shadow: "0 20px 44px rgba(15,23,42,0.55), 0 0 0 1px rgba(13,148,136,0.35)",
    heroClass: "h-[210px]",
    fade: "linear-gradient(180deg, transparent, #020617)",
    badgeClass: "border border-[rgba(201,162,39,0.4)] bg-gradient-to-r from-[#0f766e] to-[#0F172A] font-extrabold tracking-[0.18em] text-[#e8d5a3]",
    panelClass: "bg-[#020617] text-white",
    titleClass: "text-[22px] font-extrabold text-white",
    accentClass: "text-[#e8d5a3]",
    featuresClass: "font-medium text-[#94a3b8]",
    streetClass: darkStreet,
    cityClass: darkCity,
    amenityClass: "text-white",
    chipClass: GOLD_CHIP,
    chipGoldClass: GOLD_CHIP,
    chipTealClass: `${CHIP} border-[rgba(94,234,212,0.4)] text-[#5eead4] bg-[rgba(13,148,136,0.12)]`,
    priceClass: "text-[22px] font-extrabold text-[#e8d5a3]",
    shootClass: "text-[10px] font-bold text-white",
    photoClass: "",
    placeholderClass: "bg-gradient-to-b from-slate-800 to-black",
  }),
};

export function skinTheme(look: ListingCardLook): SkinTheme {
  return SKIN_THEMES[look];
}

